name: Cron

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Trigger build on dockerhub
        run: curl -X POST ${{ secrets.TRIGGERURL }}
